USE DATABASE EV_PROJECT_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE VIEW CURATED.EV_ANOMALIES AS
WITH STATS AS (
    SELECT
        AVG(BATTERY_HEALTH_INDEX) AS AVG_BH,
        STDDEV(BATTERY_HEALTH_INDEX) AS SD_BH,

        AVG(MOTOR_STRESS_INDEX) AS AVG_MS,
        STDDEV(MOTOR_STRESS_INDEX) AS SD_MS,

        AVG(USAGE_STRESS_SCORE) AS AVG_US,
        STDDEV(USAGE_STRESS_SCORE) AS SD_US
    FROM CURATED.EV_TELEMETRY_CURATED
)
SELECT
    T.EVENT_TIMESTAMP,
    T.BATTERY_HEALTH_INDEX,
    T.MOTOR_STRESS_INDEX,
    T.USAGE_STRESS_SCORE,

    CASE
        WHEN T.BATTERY_HEALTH_INDEX < (S.AVG_BH - 2 * S.SD_BH)
            THEN 'BATTERY_DEGRADATION'
        WHEN T.MOTOR_STRESS_INDEX > (S.AVG_MS + 2 * S.SD_MS)
            THEN 'MOTOR_OVERSTRESS'
        WHEN T.USAGE_STRESS_SCORE > (S.AVG_US + 2 * S.SD_US)
            THEN 'USAGE_OVERLOAD'
        ELSE 'NORMAL'
    END AS ANOMALY_TYPE,

    CASE
        WHEN T.BATTERY_HEALTH_INDEX < (S.AVG_BH - 2 * S.SD_BH)
          OR T.MOTOR_STRESS_INDEX > (S.AVG_MS + 2 * S.SD_MS)
          OR T.USAGE_STRESS_SCORE > (S.AVG_US + 2 * S.SD_US)
        THEN 1 ELSE 0
    END AS IS_ANOMALY
FROM CURATED.EV_TELEMETRY_CURATED T
CROSS JOIN STATS S;
