USE DATABASE EV_PROJECT_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE VIEW CURATED.EV_FAILURE_FORECAST_30D AS
SELECT
    EVENT_TIMESTAMP,
    BATTERY_HEALTH_INDEX,
    MOTOR_STRESS_INDEX,
    USAGE_STRESS_SCORE,
    FAILURE_PROBABILITY,
    RUL,

    CASE
        WHEN FAILURE_PROBABILITY > 0.7 OR RUL < 30
        THEN 'HIGH_RISK_NEXT_30_DAYS'
        WHEN FAILURE_PROBABILITY BETWEEN 0.4 AND 0.7
        THEN 'MEDIUM_RISK'
        ELSE 'LOW_RISK'
    END AS FAILURE_RISK_LEVEL
FROM CURATED.EV_TELEMETRY_CURATED;

