SELECT
    (SELECT COUNT(*) FROM CURATED.EV_TELEMETRY_CURATED) AS TOTAL_EVENTS,
    (SELECT SUM(IS_ANOMALY) FROM CURATED.EV_ANOMALIES) AS TOTAL_ANOMALIES,
    (SELECT ROUND(AVG(FAILURE_PROBABILITY), 3) FROM CURATED.EV_TELEMETRY_CURATED) AS AVG_FAILURE_PROB,
    (SELECT COUNT(*) FROM CURATED.EV_FAILURE_FORECAST_30D
     WHERE FAILURE_RISK_LEVEL = 'HIGH_RISK_NEXT_30_DAYS') AS HIGH_RISK_VEHICLES;

SELECT
    EVENT_TIMESTAMP,
    FAILURE_RISK_LEVEL,
    MAINTENANCE_RECOMMENDATION
FROM EV_PREDICTIVE_MAINTENANCE_AGENT
LIMIT 5;

SELECT
    EVENT_TIMESTAMP,
    ANOMALY_TYPE,
    AI_QUALITY_INSIGHT
FROM EV_QUALITY_MONITORING_AGENT
LIMIT 5;

SELECT
    EVENT_TIMESTAMP,
    ANOMALY_TYPE,
    ROOT_CAUSE_ANALYSIS
FROM EV_ROOT_CAUSE_AGENT
LIMIT 5;