use database EV_PROJECT_DB;
USE SCHEMA CURATED;

SELECT COUNT(*) FROM RAW.EV_TELEMETRY_RAW;
 
SELECT COUNT(*) FROM CURATED.EV_TELEMETRY_CURATED;
 
SELECT ANOMALY_TYPE, COUNT(*)
FROM CURATED.EV_ANOMALIES
GROUP BY ANOMALY_TYPE;
 
SELECT FAILURE_RISK_LEVEL, COUNT(*)
FROM CURATED.EV_FAILURE_FORECAST_30D
GROUP BY FAILURE_RISK_LEVEL;

SELECT *
FROM EV_ROOT_CAUSE_AGENT
WHERE ANOMALY_TYPE = 'BATTERY_DEGRADATION'
LIMIT 10;

SELECT *
FROM EV_PREDICTIVE_MAINTENANCE_AGENT
WHERE FAILURE_RISK_LEVEL = 'HIGH_RISK_NEXT_30_DAYS'
LIMIT 10;

SELECT EVENT_TIMESTAMP, ANOMALY_TYPE, AI_QUALITY_INSIGHT
FROM EV_QUALITY_MONITORING_AGENT
LIMIT 3;

SELECT
    EVENT_TIMESTAMP,
    FAILURE_RISK_LEVEL,
    MAINTENANCE_RECOMMENDATION
FROM EV_PREDICTIVE_MAINTENANCE_AGENT
LIMIT 250;