USE DATABASE EV_PROJECT_DB;
CREATE SCHEMA IF NOT EXISTS CURATED;
USE SCHEMA CURATED;

CREATE OR REPLACE VIEW CURATED.EV_TELEMETRY_CURATED AS
SELECT
    EVENT_TIMESTAMP,

    SOC,
    SOH,
    BATTERY_VOLTAGE,
    BATTERY_CURRENT,
    BATTERY_TEMPERATURE,
    CHARGE_CYCLES,

    MOTOR_TEMPERATURE,
    MOTOR_VIBRATION,
    MOTOR_TORQUE,
    MOTOR_RPM,

    DRIVING_SPEED,
    DISTANCE_TRAVELED,
    LOAD_WEIGHT,
    IDLE_TIME,

    (SOC * SOH) AS BATTERY_HEALTH_INDEX,
    (MOTOR_TEMPERATURE * MOTOR_VIBRATION * MOTOR_TORQUE) AS MOTOR_STRESS_INDEX,
    (DRIVING_SPEED * LOAD_WEIGHT) AS USAGE_STRESS_SCORE,

    RUL,
    FAILURE_PROBABILITY,
    COMPONENT_HEALTH_SCORE
FROM RAW.EV_TELEMETRY_RAW;