CREATE DATABASE EV_PROJECT_DB;
USE DATABASE EV_PROJECT_DB;

CREATE SCHEMA RAW;
USE SCHEMA RAW;

SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();

CREATE TABLE EV_TELEMETRY_RAW (
    EVENT_TIMESTAMP TIMESTAMP_NTZ,
    SOC FLOAT,
    SOH FLOAT,
    BATTERY_VOLTAGE FLOAT,
    BATTERY_CURRENT FLOAT,
    BATTERY_TEMPERATURE FLOAT,
    CHARGE_CYCLES FLOAT,
    MOTOR_TEMPERATURE FLOAT,
    MOTOR_VIBRATION FLOAT,
    MOTOR_TORQUE FLOAT,
    MOTOR_RPM FLOAT,
    POWER_CONSUMPTION FLOAT,
    BRAKE_PAD_WEAR FLOAT,
    BRAKE_PRESSURE FLOAT,
    REG_BRAKE_EFFICIENCY FLOAT,
    TIRE_PRESSURE FLOAT,
    TIRE_TEMPERATURE FLOAT,
    SUSPENSION_LOAD FLOAT,
    AMBIENT_TEMPERATURE FLOAT,
    AMBIENT_HUMIDITY FLOAT,
    LOAD_WEIGHT FLOAT,
    DRIVING_SPEED FLOAT,
    DISTANCE_TRAVELED FLOAT,
    IDLE_TIME FLOAT,
    ROUTE_ROUGHNESS FLOAT,
    RUL FLOAT,
    FAILURE_PROBABILITY FLOAT,
    MAINTENANCE_TYPE INTEGER,
    TTF FLOAT,
    COMPONENT_HEALTH_SCORE FLOAT
);


DESCRIBE TABLE EV_TELEMETRY_RAW;

CREATE FILE FORMAT EV_CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL','null','')
TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS'
ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE STAGE EV_STAGE
FILE_FORMAT = EV_CSV_FORMAT;

SHOW STAGES;

LIST @EV_STAGE;

COPY INTO EV_TELEMETRY_RAW
FROM @EV_STAGE
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) FROM EV_TELEMETRY_RAW;

SELECT
  EVENT_TIMESTAMP,
  SOC,
  SOH,
  BATTERY_VOLTAGE
FROM EV_TELEMETRY_RAW
LIMIT 10;
